[build]
builder = "nixpacks"

[build.nixpacks]
aptPkgs = []

[deploy]
startCommand = "bash start.sh"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[deploy.volumes]]
mountPath = "/app/models"
name = "rally-models"
